---
title: "Assignment3_Group6"
author:
- familyname: Makornkhan
  othernames: Chatpisut
  address: Monash University
  email: cmak0010@student.monash.edu
  correspondingauthor: true
  qualifications:  Master of Business Analytics
- familyname: YANG
  othernames: BINGYU
  address: Monash University
  email: byan0033@student.monash.edu
  qualifications: Master of Business Analytics
- familyname: Trinh
  othernames: Phuong
  address: Monash University
  email: ptri0004@student.monash.edu
  correspondingauthor: true
  qualifications:  Master of Business Analytics
department: Faculty of \newline Business &\newline Economics
organization: Monash University
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: true
---


```{r, echo = FALSE, message = FALSE, warning = FALSE}
# Libraries

library(tidyverse)
library(readr)
library(kableExtra)
library(bookdown)

```

## Section 3

\section*{Thailand and Ethiopia}

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H')
```

```{r read data, echo = FALSE, message = FALSE, warning = FALSE}
air_pollution <- read.csv("Data/death-rates-from-air-pollution.csv")
```

```{r filter data, echo = FALSE, message = FALSE, warning = FALSE}
data_Thailand <- air_pollution %>% 
  filter(Entity == "Thailand")

data_Ethiopia <- air_pollution %>% 
  filter(Entity == "Ethiopia")
```

```{r filter data2, echo = FALSE, message = FALSE, warning = FALSE}
data_Countries <- air_pollution %>% 
  filter(Entity %in% c("Thailand", "Ethiopia"))
```

### Section 3 - Introduction

XXX
